import test from 'node:test';
import assert from 'node:assert/strict';
import {MONTHLY_PRICE,seed,visibleOffices,indicators,stageOf,validateOffice,normalizePhone,validatePrices,transition,csv,isValidState} from '../lib/offices.mjs';
test('subscription test price remains SAR 196',()=>assert.equal(MONTHLY_PRICE,196));
test('administrator sees all 8 sample offices',()=>assert.equal(visibleOffices(seed(),'admin').length,8));
test('marketer preview is scoped to assigned offices',()=>{const list=visibleOffices(seed(),'marketer');assert.equal(list.length,5);assert(list.every(o=>o.assignee==='m1'));});
test('interest and trial are not counted as paid',()=>{const m=indicators(seed().offices,[]);assert.equal(m.paid,1);assert.equal(m.mrr,196);assert.equal(m.interested,4);});
test('empty data produce zero metrics, not fixed KPI values',()=>assert.equal(indicators([],[]).total,0));
test('Saudi phones are normalized',()=>assert.equal(normalizePhone('٠٥٠ ١٢٣ ٤٥٦٧'),'+966501234567'));
test('duplicate phone is rejected',()=>assert.throws(()=>validateOffice({name:'Second',city:'Riyadh',contact:'Test',phone:'0501234567'},[{id:'1',name:'First',city:'Riyadh',phone:'+966501234567'}]),/مسجل/));
test('missing required office fields are rejected',()=>assert.throws(()=>validateOffice({name:'',city:'',contact:''}),/مطلوبة/));
test('pricing answers must be complete and ordered; never reorder answers',()=>{assert.equal(validatePrices(['','','','']),null);assert.deepEqual(validatePrices([50,100,200,300]),[50,100,200,300]);assert.throws(()=>validatePrices([100,50,200,300]),/ترتيب/);assert.throws(()=>validatePrices([50,'',200,300]),/الأربعة/)});
test('trial activation requires admin role',()=>assert.throws(()=>transition(seed().offices[2],'trial','marketer'),/صلاحيات/));
test('contact consent is required for trial interest',()=>assert.throws(()=>transition(seed().offices[7],'interest','admin'),/موافقة/));
test('assignment checked in domain transition',()=>assert.throws(()=>transition(seed().offices[5],'interest','marketer'),/مسند/));
test('paid activation is disabled in the demo',()=>assert.throws(()=>transition(seed().offices[2],'paid','admin'),/غير متاح/));
test('trial transition preserves interview history',()=>{const o=seed().offices[2];const updated=transition(o,'trial','admin','2026-10-05');assert.equal(updated.trialAt,'2026-10-05');assert.equal(updated.interviewedAt,o.interviewedAt);assert.equal(stageOf(updated),'trial')});
test('CSV escapes formula injection and quotation marks',()=>{const s=csv([['=1+1','a"b','+123']]);assert(s.includes("'=1+1"));assert(s.includes('a""b'));assert(s.includes("'+123"))});
test('stored payload shape is validated',()=>{assert(isValidState(seed()));assert(!isValidState({version:1,offices:[{}]}))});
