'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {signOut} from '../app/login/actions';
import {Icon,Brand} from './icons';
import {MONTHLY_PRICE,STORAGE_KEY,MARKETERS,STAGES,localDate,uid,seed,stageOf,visibleOffices,validateOffice,validatePrices,transition,indicators,csv,isValidState} from '../lib/offices.mjs';
const labels=Object.fromEntries(STAGES);
const navs=[['home','نظرة عامة','home'],['offices','المكاتب المشاركة','building'],['interviews','المقابلات','chat'],['trials','التجربة الأولية','trial'],['tasks','المهام والمتابعات','tasks'],['subscriptions','الاشتراكات','card'],['reports','التقارير','chart'],['team','فريق التسويق','users']];
function Badge({office}){return <span className={`badge ${stageOf(office)}`}>{labels[stageOf(office)]}</span>}
function Modal({title,children,onClose}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={onClose}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" aria-label="إغلاق" onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>}
export default function OfficeConsole({role,live=false,staff=null}){
 const [db,setDB]=useState(null),[page,setPage]=useState('home'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('o1'),[modal,setModal]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[storageWarning,setStorageWarning]=useState(false),[wideText,setWideText]=useState(false);
 const admin=role==='admin';
 const [busy,setBusy]=useState(false),[loadError,setLoadError]=useState('');const inFlight=useRef(false);
 const marketers=live?(db?.marketers||[]):MARKETERS;
 async function refresh(){const response=await fetch('/api/console/',{cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error||'تعذر تحميل البيانات.');setDB(value);setLoadError('');}
 async function remote(action,officeId,data={}){if(inFlight.current)throw Error('انتظر اكتمال الحفظ الحالي.');inFlight.current=true;setBusy(true);try{const response=await fetch('/api/console/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,officeId,data})});const value=await response.json();if(!response.ok)throw Error(value.error||'تعذر الحفظ.');try{await refresh();setNotice('تم الحفظ في قاعدة بيانات لِقا.');}catch{setNotice('تم الحفظ، لكن تعذر تحديث العرض. حدّث الصفحة ولا تكرر الإرسال.');}return value;}finally{setBusy(false);inFlight.current=false;}}
 useEffect(()=>{if(live){refresh().catch(e=>setLoadError(e.message));return;}try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(!isValidState(parsed))throw Error('corrupt');setDB(parsed)}else setDB(seed())}catch{setStorageWarning(true);setDB(seed())}},[]);
 useEffect(()=>{if(!db||live)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}catch{setStorageWarning(true)}},[db]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id)},[notice]);
 const offices=useMemo(()=>db?(live?db.offices:visibleOffices(db,role)):[],[db,role,live]);
 const current=offices.find(o=>o.id===selected)||offices[0];
 const metrics=indicators(offices,db?.tasks||[]);
 const scopedTasks=(db?.tasks||[]).filter(t=>offices.some(o=>o.id===t.officeId));
 const filtered=offices.filter(o=>(filter==='all'||stageOf(o)===filter)&&`${o.name} ${o.city} ${o.district} ${o.contact}`.includes(query));
 const shown=page==='trials'?filtered.filter(o=>o.interestedAt):filtered;
 function open(type,office=current){setError('');setModal({type,officeId:office?.id})}
 function commit(next,action,officeId=null){if(live)throw Error('تستخدم هذه الواجهة الحفظ عبر الخادم فقط.');next.logs.unshift({id:uid(),action,officeId,at:new Date().toISOString(),actor:admin?'إدارة لِقا':'المسوق عبدالله'});setDB(next)}
 function editOffice(id,update,action){const next=structuredClone(db);const o=offices.find(x=>x.id===id);if(!o)return;next.offices=next.offices.map(x=>x.id===id?update(x):x);commit(next,action,id)}
 async function act(action,office=current){try{if(live){await remote(action,office.id);return;}editOffice(office.id,o=>transition(o,action,role),`${{interest:'تسجيل الموافقة على التجربة',prototype:'تسجيل تجربة النموذج',trial:'توثيق بدء التجربة'}[action]} — ${office.name}`);setNotice('تم تحديث الملف في النسخة التجريبية.')}catch(e){setNotice(e.message)}}
 function go(id){setPage(id);setFilter('all');setMenu(false);setQuery('')}
 function download(){const rows=[['اسم المكتب','المدينة','الحي','المسؤول','المرحلة','المكلف','السعر المقترح'],...shown.map(o=>[o.name,o.city,o.district,o.contact,labels[stageOf(o)],marketers.find(m=>m.id===o.assignee)?.name,MONTHLY_PRICE])];const url=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=live?'liqa-offices.csv':'liqa-offices-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('تم تصدير النتائج الظاهرة فقط.');}
 async function formSubmit(event){event.preventDefault();setError('');const data=Object.fromEntries(new FormData(event.currentTarget));const original=offices.find(o=>o.id===modal.officeId);try{
   if(live){
    const action={office:'create',edit:'edit',note:'note',interview:'interview',task:'task'}[modal.type];
    const officeId=action==='create'?null:action==='task'?data.officeId:original?.id;
    const payload={...data,assignee:data.assignee||staff.user_id,version:original?.version};
    const result=await remote(action,officeId,payload);setSelected(result.id);setModal(null);return;
   }
   if(modal.type==='office'||modal.type==='edit'){
    const values=validateOffice({...data,assignee:admin?data.assignee:'m1'},db.offices,modal.type==='edit'?original.id:'');
    const today=localDate();const consent=Boolean(data.consent);const record={...(modal.type==='edit'?original:{}),...values,id:modal.type==='edit'?original.id:uid(),createdAt:original?.createdAt||today,updatedAt:today,consentAt:consent?(original?.consentAt||today):null,notes:modal.type==='edit'?original.notes:[]};
    delete record.consent;
    if(modal.type==='edit')editOffice(original.id,()=>record,'تعديل بيانات المكتب والموافقة');else{const next=structuredClone(db);next.offices.unshift(record);commit(next,'إضافة مكتب بموافقة مستقلة',record.id)}setSelected(record.id);
   }else if(modal.type==='note'){
    if(!data.text?.trim())throw Error('اكتب الملاحظة أولًا.');editOffice(original.id,o=>({...o,updatedAt:localDate(),notes:[{id:uid(),text:data.text.trim(),at:localDate(),author:admin?'الإدارة':'عبدالله'},...o.notes]}),'إضافة ملاحظة ميدانية');
   }else if(modal.type==='interview'){
    if(!data.researchConsent)throw Error('يلزم توثيق موافقة المشاركة في المقابلة.');
    const prices=validatePrices([data.p1,data.p2,data.p3,data.p4]);const next=structuredClone(db);next.interviews.unshift({id:uid(),officeId:original.id,date:localDate(),workflow:data.workflow,pain:data.pain,prices,consent:true});next.offices=next.offices.map(o=>o.id===original.id?{...o,interviewedAt:o.interviewedAt||localDate(),updatedAt:localDate()}:o);commit(next,'توثيق مقابلة وموافقة بحثية',original.id);
   }else if(modal.type==='task'){
    if(!data.title?.trim()||!data.due)throw Error('اكتب المهمة وحدد الموعد.');if(!offices.some(o=>o.id===data.officeId))throw Error('اختر مكتبًا ضمن نطاقك.');const next=structuredClone(db);next.tasks.unshift({id:uid(),officeId:data.officeId,title:data.title.trim(),due:data.due,done:false});commit(next,'جدولة متابعة',data.officeId);
   }
   setModal(null);setNotice('تم الحفظ في بيانات العرض على هذا المتصفح.');
 }catch(e){setError(e.message)}}
 async function completeTask(task){if(live){try{await remote('complete',task.officeId,{taskId:task.id,done:!task.done})}catch(e){setNotice(e.message)}return;}const next=structuredClone(db);next.tasks=next.tasks.map(t=>t.id===task.id?{...t,done:!t.done}:t);commit(next,task.done?'إعادة فتح متابعة':'إنجاز متابعة',task.officeId)}
 if(!db)return <main className="loading" dir="rtl"><div><Brand/><p role={loadError?'alert':'status'}>{loadError||'جاري تجهيز مساحة لِقا…'}</p>{loadError&&<><button className="primary" onClick={()=>refresh().catch(e=>setLoadError(e.message))}>إعادة المحاولة</button><p><Link href="/login/">العودة للدخول</Link></p></>}</div></main>;
 const picked=modal?offices.find(o=>o.id===modal.officeId):null;
 const title=page==='home'?(admin?'لوحة إدارة المكاتب المشاركة':'لوحة تحكم المسوق'):navs.find(n=>n[0]===page)?.[1];
 const counters=admin?[['إجمالي المكاتب',metrics.total,'building'],['أكملوا المقابلة',metrics.interviewed,'chat'],['وافقوا على التجربة',metrics.interested,'trial'],[live?'بدؤوا التجربة':'حسابات تجريبية',metrics.trial,'users'],[live?'مشتركون مؤكدون':'مشتركون · مثال',metrics.paid,'card']]:[['المكاتب المسندة إليّ',metrics.total,'building'],['مقابلات مكتملة',metrics.interviewed,'chat'],['متابعات مفتوحة',metrics.pending,'tasks'],[live?'بدؤوا التجربة':'حسابات التجربة',metrics.trial,'trial'],[live?'مشتركون مؤكدون':'مشتركون · مثال',metrics.paid,'card']];
 return <div className={`shell ${wideText?'large-type':''}`} dir="rtl" aria-busy={busy}>
  <a className="skip" href="#main">تجاوز القائمة إلى المحتوى</a>
  {menu&&<button className="menu-mask" onClick={()=>setMenu(false)} aria-label="إغلاق القائمة"/>}
  <aside className={`sidebar ${menu?'open':''}`}><Link href="/" aria-label="لِقا — اختيار مساحة العمل"><Brand/></Link><nav>{navs.filter(n=>admin||n[0]!=='team').map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon name={icon}/>{id==='offices'&&!admin?'المكاتب المسجلة':label}{id==='tasks'&&metrics.pending>0&&<em>{metrics.pending}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-quote">معًا<br/>لأسواق عقارية<br/><b>أكثر ازدهارًا.</b></div><small>A VENTURE BY<br/><strong>AMAN INNOVATION GROUP</strong><br/>MALAYSIA · FIELD CONSOLE 0.2</small></div></aside>
  <div className="workspace"><header className="topbar"><div className="welcome"><button className="icon-btn mobile-menu" aria-label="فتح القائمة" onClick={()=>setMenu(true)}><Icon name="menu"/></button><div><b>مرحبًا {live?staff.display_name:admin?'بفريق الإدارة':'عبدالله'}</b><small>معًا نبني مستقبل الوساطة العقارية</small></div></div><label className="global-search"><Icon name="search"/><input aria-label="البحث عن مكتب أو مدينة أو مسؤول" placeholder="البحث عن مكتب، مدينة أو مسؤول…" value={query} onChange={e=>{setQuery(e.target.value);if(!['home','offices','trials'].includes(page))setPage('offices')}}/><kbd>بحث</kbd></label><div className="top-controls"><button className="icon-btn" onClick={()=>go('tasks')} aria-label="المتابعات"><Icon name="bell"/>{metrics.pending>0&&<i/>}</button><button className="text-size" onClick={()=>setWideText(!wideText)} aria-pressed={wideText}>أ أ</button><div className="account"><span className="avatar">{admin?'إ':'ع'}</span><div><b>{live?staff.display_name:admin?'إدارة لِقا':'عبدالله · تجريبي'}</b><small>{admin?'مسؤول المنصة':'المسوق الميداني'}</small></div></div></div></header>
  <main id="main"><div className="demo-bar"><Icon name="shield" size={16}/><span>{live?'مساحة الفريق · الصلاحيات والحفظ عبر الخادم · التحصيل المالي غير مفعّل.':'بيئة عرض · أسماء وأرقام توضيحية · حفظ على هذا المتصفح فقط · ليست حسابات آمنة أو تحصيلًا فعليًا.'}</span>{live?<form action={signOut}><button className="small-button" type="submit">تسجيل الخروج</button></form>:<Link href={admin?'/demo/marketer/':'/demo/admin/'}>تجربة دور {admin?'المسوق':'الأدمن'} <Icon name="arrow" size={15}/></Link>}</div>{busy&&<p role="status" className="hint">جارٍ حفظ التغيير…</p>}{storageWarning&&<p role="alert" className="warning">تعذر قراءة الحفظ المحلي أو كانت البيانات غير صالحة. استخدم التصدير؛ البيانات الحالية قد تبقى للجلسة فقط.</p>}
  <div className="page-head"><div><h1>{title}</h1><p>{admin?'متابعة رحلة المكاتب من البحث والمقابلات حتى تجربة المنتج والاشتراك.':'إدارة تسجيل المكاتب والشركات العقارية ومتابعة خطوتها القادمة.'}</p></div><span className="date"><Icon name="calendar" size={18}/>{localDate()}</span></div>
  {['home','offices','trials'].includes(page)&&<>
   {page==='home'&&<><div className="stats">{counters.map(([label,value,icon],i)=><article className={`stat ${i===4?'featured':''}`} key={label}><span className={`stat-icon s${i}`}><Icon name={icon}/></span><small>{label}</small><b>{value}</b><span>{live?(i===4?'مدفوعات مؤكدة فقط':'محسوب من السجلات المتاحة'):i===4?'بيانات اشتراك افتراضية':'محسوب من سجلات العرض'}</span></article>)}</div>{admin?<section className="panel journey"><div><h2>مراحل رحلة المكتب</h2><p>أعداد الوصول إلى كل مرحلة — ليست نسبًا بحثية</p></div><div className="journey-steps">{STAGES.slice(1).map(([id,label])=><button key={id} onClick={()=>{setPage('offices');setFilter(id)}}><span>{label}</span><b>{offices.filter(o=>id==='interviewed'?o.interviewedAt:id==='interested'?o.interestedAt:id==='prototype'?o.prototypeAt:id==='trial'?o.trialAt:o.paidAt).length}</b></button>)}</div></section>:<section className="panel registration-call"><div className="call-copy"><span className="circle"><Icon name="building" size={26}/></span><div><h2>ابدأ علاقة مع مكتب جديد</h2><p>سجل الاهتمام بموافقة واضحة، ثم رتّب الخطوة التالية.</p></div></div><button className="primary" onClick={()=>open('office')}><Icon name="plus"/>تسجيل مكتب جديد</button><div className="price-label"><small>سعر الاشتراك المقترح للاختبار</small><b>196 ريال / شهريًا</b></div></section>}</>}
   <div className="data-layout"><section className="panel table-panel"><div className="toolbar"><div className="actions"><button className="primary" onClick={()=>open('office')}><Icon name="plus" size={17}/>إضافة مكتب</button><button onClick={()=>open('interview')} disabled={!current}><Icon name="chat" size={17}/>تسجيل مقابلة</button><button onClick={()=>open('invite')} disabled={!current}><Icon name="send" size={17}/>دعوة للتجربة</button></div><button onClick={download}><Icon name="download" size={17}/>تصدير</button></div><div className="table-filters"><label><Icon name="search" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث في المكاتب…" aria-label="بحث في المكاتب"/></label><select aria-label="تصفية حسب المرحلة" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">جميع المراحل</option>{STAGES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><span>{shown.length} مكتب</span></div>
   <div className="table-scroll"><table><thead><tr><th>المكتب / الشركة</th><th>المدينة / الحي</th><th>المسؤول</th><th>حالة المشاركة</th><th>الخطوة التالية</th>{admin&&<th>المكلف</th>}<th>إجراءات</th></tr></thead><tbody>{shown.map(o=>{const task=db.tasks.find(t=>t.officeId===o.id&&!t.done);return <tr className={current?.id===o.id?'selected':''} key={o.id}><td><button className="office-name" onClick={()=>setSelected(o.id)}><span className="office-logo"><Icon name="building"/></span><b>{o.name}</b></button></td><td>{o.city}<small>{o.district}</small></td><td>{o.contact}</td><td><Badge office={o}/></td><td>{task?.title||'حدد إجراءً تاليًا'}<small>{task?.due||'—'}</small></td>{admin&&<td>{marketers.find(m=>m.id===o.assignee)?.name.split(' · ')[0]}</td>}<td><button className="small-button" onClick={()=>{setSelected(o.id);open('edit',o)}}>فتح الملف</button></td></tr>})}</tbody></table>{!shown.length&&<div className="empty"><Icon name="search" size={30}/><h3>لا توجد مكاتب مطابقة</h3><p>غيّر البحث أو المرشح، أو أضف مكتبًا جديدًا.</p><button onClick={()=>{setFilter('all');setQuery('')}}>مسح الفلاتر</button></div>}</div></section>
   <aside className="panel profile">{current?<><div className="panel-title"><h2>ملف المكتب المحدد</h2><span className="circle"><Icon name="building"/></span></div><h3>{current.name}</h3><Badge office={current}/><p className="location"><Icon name="pin" size={17}/>{current.city} — {current.district}</p><dl><dt>المسؤول</dt><dd>{current.contact}</dd><dt>رقم التواصل</dt><dd dir="ltr">{current.phone||'غير مضاف'}</dd><dt>مصدر التعارف</dt><dd>{current.source}</dd><dt>موافقة التواصل</dt><dd><span className={`badge ${current.consentAt?'interested':'registered'}`}>{current.consentAt?'موثقة':'غير موثقة'}</span></dd><dt>مستوى الاهتمام</dt><dd>{current.interest}</dd></dl><div className="profile-note"><h4>آخر ملاحظة</h4><p>{current.notes[0]?.text||'لا توجد ملاحظات بعد.'}</p></div><div className="profile-next"><Icon name="calendar"/><div><small>الخطوة القادمة</small><b>{db.tasks.find(t=>t.officeId===current.id&&!t.done)?.title||'رتّب متابعة للمكتب'}</b></div></div><button className="primary full" onClick={()=>open('edit')}><Icon name="arrow"/>فتح ملف المكتب</button><div className="profile-buttons"><button onClick={()=>open('note')}><Icon name="note" size={16}/>ملاحظة</button><button onClick={()=>open('task')}><Icon name="plus" size={16}/>متابعة</button></div></>:<div className="empty">أضف مكتبك الأول للبدء.</div>}</aside></div>
  </>}
  {page==='interviews'&&<section className="panel"><div className="panel-title"><div><h2>مقابلات موثقة، وقرارات أوضح</h2><p>موافقة البحث منفصلة عن قبول التواصل والاشتراك.</p></div><button className="primary" onClick={()=>open('interview')} disabled={!current}><Icon name="plus"/>تسجيل مقابلة</button></div>{db.interviews.filter(i=>offices.some(o=>o.id===i.officeId)).length?db.interviews.filter(i=>offices.some(o=>o.id===i.officeId)).map(i=><article className="record" key={i.id}><span className="circle"><Icon name="chat"/></span><div><h3>{offices.find(o=>o.id===i.officeId)?.name}</h3><p>{i.workflow} · {i.pain||'لا توجد ملاحظة إضافية'}</p><small>{i.date} · {i.prices?'أُدخلت إجابات حساسية السعر':'لم يُختبر السعر'}</small></div></article>):<div className="empty"><Icon name="chat" size={32}/><h3>ابدأ بتوثيق أول مقابلة</h3><p>{live?'لا توجد مقابلات مسجلة ضمن نطاقك بعد.':'حالات اللوحة الأولية بيانات توضيحية؛ لا توجد استجابات بحث فعلية في هذه البيئة.'}</p></div>}</section>}
  {page==='tasks'&&<section className="panel"><div className="panel-title"><div><h2>كل زيارة، تتبعها خطوة واضحة</h2><p>{metrics.pending} متابعة مفتوحة في نطاقك</p></div><button className="primary" onClick={()=>open('task')} disabled={!current}><Icon name="plus"/>متابعة جديدة</button></div>{scopedTasks.map(t=><article className={`record ${t.done?'done':''}`} key={t.id}><button className={`task-check ${t.done?'checked':''}`} aria-label={t.done?'إعادة فتح المهمة':'إنجاز المهمة'} onClick={()=>completeTask(t)}>{t.done&&<Icon name="check" size={17}/>}</button><div><h3>{t.title}</h3><p>{offices.find(o=>o.id===t.officeId)?.name}</p></div><span className="due"><Icon name="calendar" size={15}/>{t.due}</span></article>)}{!scopedTasks.length&&<div className="empty">لا توجد متابعات؛ أنشئ أول مهمة.</div>}</section>}
  {page==='subscriptions'&&<section className="panel"><div className="panel-title"><div><h2>الاشتراك لا يبدأ بتسجيل الاهتمام</h2><p>سعر اختبار موحد: <strong>196 ريالًا شهريًا</strong>. التفعيل المدفوع والتحصيل الفعلي معطلان في هذه الدفعة.</p></div><span className="badge registered">{live?'متابعة الاشتراكات · التحصيل غير مفعل':'محاكاة إدارية فقط'}</span></div><div className="table-scroll"><table><thead><tr><th>المكتب</th><th>المرحلة</th><th>موافقة التواصل</th><th>السعر الشهري</th><th>الإجراء</th></tr></thead><tbody>{offices.map(o=><tr key={o.id}><td>{o.name}</td><td><Badge office={o}/></td><td>{o.consentAt?'موثقة':'غير موثقة'}</td><td>196 ريال</td><td>{o.paidAt?<span className="badge paid">{live?'دفعة موثقة من مزود التحصيل':'سجل افتراضي؛ لا دفعة حقيقية'}</span>:admin?<button disabled={!!o.trialAt||busy} onClick={()=>act('trial',o)}>{o.trialAt?'بداية التجربة موثقة':'توثيق بدء التجربة'}</button>:<button onClick={()=>open('invite',o)}>معاينة الدعوة</button>}</td></tr>)}</tbody></table></div><p className="hint">صلاحية التحصيل من واجهة الإدارة ستُربط بتأكيد دفع من الخادم. لا يستطيع المسوق تعليم المكتب كعميل مدفوع.</p></section>}
  {page==='team'&&admin&&<section className="panel"><div className="panel-title"><h2>توزيع المكاتب على فريق التسويق</h2><span className="badge registered">{live?'فريق لِقا':'فريق توضيحي'}</span></div><div className="team-grid">{marketers.map(m=><article className="team-card" key={m.id}><span className="avatar">{m.name[0]}</span><h3>{m.name}</h3><b>{db.offices.filter(o=>o.assignee===m.id).length} مكاتب</b><p>يمكن تغيير التكليف من ملف المكتب.</p></article>)}</div></section>}
  {(page==='home'||page==='reports')&&<div className="bottom-grid"><section className="panel"><div className="panel-title"><h2>ملاحظات البحث الميداني</h2><button className="small-button" onClick={()=>open('note')} disabled={!current}><Icon name="plus" size={15}/>إضافة</button></div>{offices.flatMap(o=>o.notes.slice(0,1).map(n=>({...n,office:o.name}))).slice(0,4).map(n=><div className="note-line" key={n.id}><Icon name="note" size={17}/><div><p>{n.text}</p><small>{n.office} · {n.at}</small></div></div>)}</section><section className="panel"><h2>مؤشرات المشاركة</h2><p className="muted">{live?'نسب مشتقة من سجلات المشاركة المتاحة.':'نسب مشتقة من سجلات العرض، وليست نتائج للمسح.'}</p>{[['المقابلة',metrics.interviewed],['الموافقة',metrics.interested],['التجربة',metrics.trial],[live?'اشتراك موثق':'اشتراك توضيحي',metrics.paid]].map(([label,n])=><div className="bar-row" key={label}><span>{label}</span><div><i style={{width:`${metrics.total?100*n/metrics.total:0}%`}}/></div><b>{metrics.total?Math.round(100*n/metrics.total):0}%</b></div>)}</section><section className="quote"><span>“</span><p>كل زيارة تقرّبنا من بناء شراكة جديدة، ومعًا نصنع مستقبل الوساطة العقارية.</p><b>لِقا</b><small>أكثر من مجرد منصة</small></section></div>}
  {page==='reports'&&<section className="panel audit"><h2>سجل الإجراءات</h2>{db.logs.filter(l=>admin||offices.some(o=>o.id===l.officeId)).slice(0,30).map(l=><div className="note-line" key={l.id}><Icon name="clock" size={17}/><div><p>{l.action}</p><small>{l.actor} · {l.at.slice(0,10)}</small></div></div>)}</section>}
  <footer className="footer"><span>LIQA — WHERE DEMAND MEETS OPPORTUNITY.</span><span>{live?'لِقا · مساحة عمل الفريق المخوّل':'نسخة تطوير واجهات · لا تُدخل بيانات شخصية فعلية.'}</span></footer></main></div>
  {notice&&<div className="toast" role="status"><Icon name="check"/>{notice}</div>}
  {modal&&<Modal title={{office:'تسجيل مكتب جديد',edit:'ملف المكتب',note:'ملاحظة ميدانية',interview:'توثيق مقابلة',task:'متابعة جديدة',invite:'دعوة للمشاركة في التجربة'}[modal.type]} onClose={()=>setModal(null)}>
   {modal.type==='invite'?<div className="modal-body"><p className="hint">معاينة فقط؛ لن يُرسل أي بريد أو واتساب، ولن يُنشأ حساب حقيقي.</p><div className="invitation"><Brand/><h3>أهلًا بمكتب {picked?.name}</h3><p>ندعوكم للمشاركة في تجربة لِقا، وتنظيم العروض والطلبات بطريقة أقرب لعملكم اليومي. المشاركة اختيارية، ولا يترتب عليها تحصيل أو التزام مالي.</p></div><div className="actions"><button className="primary" disabled={!picked?.consentAt||busy} onClick={()=>{act('interest',picked);setModal(null)}}>{live?'توثيق قبول التجربة':'توثيق قبول التجربة في المثال'}</button><button onClick={()=>{setModal(null);open('edit',picked)}}>مراجعة الموافقة</button></div>{!picked?.consentAt&&<p className="warning">لا توجد موافقة تواصل موثقة؛ راجعها قبل تسجيل القبول.</p>}</div>:<form onSubmit={formSubmit} className="modal-body">
   {['office','edit'].includes(modal.type)&&<><p className="hint">{live?'تسجيل مشاركة المكتب لا ينشئ اشتراكًا مدفوعًا. وثّق الموافقة وحدد المسوق المسؤول.':'مساحة عرض محلية؛ استخدم بيانات توضيحية. التسجيل لا ينشئ اشتراكًا أو حساب مكتب تشغيليًا.'}</p><div className="form-grid"><label>اسم المكتب *<input name="name" required maxLength={100} defaultValue={modal.type==='edit'?picked?.name:''}/></label><label>المدينة *<input name="city" required maxLength={40} defaultValue={modal.type==='edit'?picked?.city:'الرياض'}/></label><label>الحي<input name="district" maxLength={60} defaultValue={modal.type==='edit'?picked?.district:''}/></label><label>اسم المسؤول *<input name="contact" required maxLength={80} defaultValue={modal.type==='edit'?picked?.contact:''}/></label><label>الجوال · اختياري<input name="phone" type="tel" dir="ltr" placeholder="05xxxxxxxx" defaultValue={modal.type==='edit'?picked?.phone:''}/></label><label>مصدر التعارف<select name="source" defaultValue={picked?.source||'زيارة ميدانية'}><option>زيارة ميدانية</option><option>إحالة شريك</option><option>اتصال وارد</option></select></label><label>مستوى الاهتمام<select name="interest" defaultValue={picked?.interest||'متوسط'}><option>عالي</option><option>متوسط</option><option>منخفض</option></select></label>{admin&&<label>المسوق المكلف<select name="assignee" defaultValue={picked?.assignee||(live?staff.user_id:'m1')}>{marketers.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label>}</div><label className="checkbox"><input type="checkbox" name="consent" defaultChecked={modal.type==='edit'&&!!picked?.consentAt}/>وافق المسؤول على التواصل لترتيب تجربة المنتج. ليست موافقة على الاشتراك المدفوع.</label>{modal.type==='edit'&&<div className="file-actions"><button type="button" disabled={!picked.interestedAt||!!picked.prototypeAt||busy} onClick={()=>{act('prototype',picked);setModal(null)}}>توثيق تجربة النموذج</button>{admin&&<button type="button" disabled={!picked.interestedAt||!!picked.trialAt||busy} onClick={()=>{act('trial',picked);setModal(null)}}>توثيق بدء التجربة</button>}</div>}</>}
   {modal.type==='note'&&<><p>{picked?.name}</p><label>الملاحظة<textarea name="text" required maxLength={1200} rows={5} placeholder="ما الذي تعلمناه؟ وما الخطوة التالية؟"/></label></>}
   {modal.type==='task'&&<><label>المكتب<select name="officeId" defaultValue={picked?.id}>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>المهمة<input name="title" required maxLength={120}/></label><label>تاريخ المتابعة<input type="date" name="due" required defaultValue={localDate()}/></label></>}
   {modal.type==='interview'&&<><p>{picked?.name}</p><label className="checkbox"><input type="checkbox" name="researchConsent" required/>وافق المشارك على المقابلة وتسجيل الإجابات لهذا البحث.</label><label>كيف يدير العروض والطلبات؟<select name="workflow"><option>واتساب</option><option>ملفات وجداول</option><option>نظام إدارة عملاء</option><option>طريقة أخرى</option></select></label><label>المشكلة الأهم بكلمات المشارك<textarea name="pain" rows={3} maxLength={1500}/></label><h3>حساسية السعر — دون عرض سعر مقترح</h3><p className="hint">أسئلة اختيارية. تُعرض الأسعار التجارية بعد اكتمال الإجابات، لا أثناءها. أكمل الأسئلة قبل عرض أي سعر مقترح. لا تشارك لوحة المشغل مع المشارك أثناء اختبار السعر.</p><div className="form-grid">{['منخفض جدًا ويثير الشك في الجودة','قيمة جيدة مقابل الخدمة','مرتفع لكن يستحق التفكير','مرتفع جدًا ولن يشترك'].map((t,i)=><label key={t}>{i+1}. {t}<input type="number" min="0" step="0.01" name={`p${i+1}`} placeholder="ريال / شهر"/></label>)}</div></>}
   {error&&<p className="warning" role="alert">{error}</p>}<div className="modal-footer"><button className="primary" type="submit" disabled={busy}><Icon name="check" size={17}/>حفظ</button><button type="button" onClick={()=>setModal(null)}>إلغاء</button></div></form>}
  </Modal>}
 </div>;
}
